# Generated by Django 5.1.2 on 2024-11-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='room',
        ),
    ]
